### ISSUE TITLE
Remove Actor.IsDisabled in favor of using IsTraitDisabled everywhere

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10237]
As mentioned in #10235, it would be better to get this out of the way first before we remove `INotifyBuildComplete`.

Since the number of places that check `self.IsDisabled()` is rather large and some related traits are not upgradable yet, I think the roadmap should look like this (exact order or number of steps might change):
## 1.
- [ ] Make all traits that need to be disabled under certain circumstances upgradable, if they aren't yet (an exception is `DisabledOverlay`, as we already have a replacement in `UpgradeOverlay`)
- [ ] Check for `IsTraitDisabled` (in addition to `self.IsDisabled()`)
## 2.
- [ ] Remove `IDisable` from traits that implement it
- [ ] Replace it on yaml level for `Husk` (as far as I can tell, apart from the overlay there currently isn't anything that requires husks being disabled anyway)
- [ ] Replace it by granting upgrades on `Power`-related traits
- [ ] Completely remove traits that become redundant (`DisabledOverlay` and `DisableOnUpgrade`)
## 3.
- [ ] Remove any remaining `self.IsDisabled()` checks from code
- [ ] Remove `Actor.IsDisabled` and the `IDisable` interface
##

**Comment by penev92** [comment]
Adding the `Next release` milestone to match the PR that closes this.
