### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10475]
Prerequisites for initial translations:
- [ ] Engine support:
  - [x] Translation support for yaml-defined strings. [#3929]
  - [ ] Translation support for code-defined strings.
  - [ ] Change server messages to send a string ID and arguments to translate client-side.
- [ ] Tooling:
  - [x] Automated chrome string extraction. [#5152]
  - [ ] Automated format string sanity checks (verify that strings with formatting parameters define the same number across all translations).
- [ ] Extract hardcoded strings into english translation.
- [ ] Extract yaml strings into english translation.
- [ ] Include language setting in crash logs.

Later improvements:
- [ ] Support for detecting/downloading/installing foreign content bundles (sound/art).  Related to the ongoing mod browser / installation work.
- [ ] Support for switching art/sounds based on translation.

**Comment by pchote** [comment]
#11375 and followups check off support for detecting/downloading/installing foreign content bundles.

**Comment by Mailaender** [comment]
I believe the whole approach taken is a dead end. Instead of building our own incompatible translation system we should try to hook up something standardized like https://github.com/neris/NGettext where tooling already exists.

**Comment by Mailaender** [comment]
I played a bit with https://crowdin.com/project/openra and yml is supported although we don't adhere to the Ruby translation system. We will need tooling that converts our `@PLACEHOLDERS@` to English, generate English to Language files for the web interface and converter Language to `@PLACEHOLDERS@` back.

**Comment by abcdefg30** [comment]
Is adding translation support to the auto generated documentation also considered as part of this ticket?

**Comment by pchote** [comment]
It is not, and I would argue against doing that (but not in this ticket).

**Comment by forcecore** [comment]
There's font problem too, the default fonts don't support CJK characters. There should be some way of providing additional fonts for the translations.

**Comment by Sav87** [comment]
Why not do a translation like this: there is a file "ra|chrome/ingame-player.yaml" and need a translation for "XXX".
So try to download it from ".\mods\ra\languages\XXX\chrome\ingame-player.yaml", if there is no file try to download ".\mods\ra\chrome\ingame-player.yaml" then the load error is mod.

**Comment by reaperrr** [comment]
In principle I'd be willing to, but I'll need some help getting my head around the "how to".
That's something for "later this year" at best, though.

**Comment by forcecore** [comment]
True, I took a look in the past but I have no idea how.

**Comment by Sav87** [comment]
I'm trying to translate the code-defined strings. Translated by LogoStripeLoadScreen.cs, IngameMenuLogic.cs, SettingsLogic.cs and ChromeLayout. [https://github.com/Sav87/OpenRA/commit/8792fefcbfcc952652bfe05bf0dc5c694b24f700](url)
Continue the translation?

**Comment by pchote** [comment]
That is pretty much the right idea, but there is an important point that you will need to consider and change.  When you have a line like `line.GetText = () => FieldLoader.Translate("STRING-ID")` this is actually a function that is called every time the game renders.  You really don't want to be retranslating these strings 60 times per second!

Instead use a pattern like this:
```csharp
var translatedStringID = FieldLoader.Translate("STRING-ID");
line.GetText = () => translatedStringID;
```

We will also need to support for map-defined translations, so your changes to `LoadTranslations` will need to be reworked.

**Comment by Sav87** [comment]
I understand the translation of MissionBrilling? and where should it be recorded? if the file 'languages/*.yaml' then this should not be a problem. If in these files there is a necessary line that without a difference for what it to use: a maps, code, chromeLayout...

**Comment by pchote** [comment]
We may want (or perhaps even need) to adopt something like https://projectfluent.org/ (developed by Mozilla) to be able to cleanly handle the dynamic messages in the chrome logic.  This should also help with the availability of standard tooling for translators.

**Comment by xan2622** [comment]
There is now a $15 usd bounty on this issue. 
https://www.bountysource.com/issues/29755626-translation-support

**Comment by muumlover** [comment]
I just saw this project today and I played it. It feels really good. If you have multi-language support, then more people should be able to experience such a great project, so I support $15 in multi-language support. I am a red alert game enthusiast, and also a program developer. If multi-language support is activated, I can also join the localization translation.

**Comment by Sav87** [comment]
@pchote Translate [Yaml](https://github.com/Sav87/OpenRA/tree/TranslateYaml) or [Fluent](https://github.com/Sav87/OpenRA/tree/TranslateFluent)?

**Comment by Mailaender** [comment]
https://github.com/cookgreen/Yuris-Revenge has a Chinese translation.

**Comment by akpellablok** [comment]
Hey guys, i just translate the text files from rules and the sound files are german now... Later i make a download file ... Maybe someone can implate this into the game :/

https://youtu.be/mSk2vXAVkKE

**Comment by AngryUbuntuNerd** [comment]
any progress on this, or guidance / ideas how we can help?

**Comment by BackMountainDevil** [comment]
> https://github.com/cookgreen/Yuris-Revenge has a Chinese translation.

Another translation about RA2 [mod](https://www.moddb.com/mods/openra-simplified-chinese-mod-series). Download [page](https://www.moddb.com/mods/openra-simplified-chinese-mod-series/downloads/openra-simplified-chinese-mod-series-release-20200510). Hope it can be set in games in the future

**Comment by Blueberryy** [comment]
How's translation system going? I want to help with Russian if it works :p

**Comment by penev92** [comment]
Hi! We are still not ready, but hopefully we could be in in time for next release.

**Comment by Blueberryy** [comment]
> Hi! We are still not ready, but hopefully we could be in in time for next release.

Oh this is nice to read. And this all really took 8 years to implement? woah

**Comment by PunkPun** [comment]
it only properly started about 2 years ago

**Comment by JovialFeline** [comment]
Should TimeLimitManager's CountdownText run through Fluent? At the moment, allies-02, allies-10a, and allies-13 use it. Its Notification may also apply.

**Comment by PunkPun** [comment]
Yes, it looks like a leftover. The `--extract-yaml-strings` command finds it in more places. D2K extraction fails because of the issue mentioned in #22022

**Comment by JimmyS83** [comment]
Would be nice to use fonts, capable to show languages depending on user locale or such. Its laying here for years https://github.com/OpenRA/OpenRA/issues/9712.
Not sure if thats mentioned to be part of Closed https://github.com/OpenRA/OpenRA/pull/17794, however..

I thinks it fair and benefitial  to bring the charset question/open discussion even before localisation. Because there is a chatroom window. And its "buggy" for players talking to each other in their own language (I guess it will be similiar case with Usernames), neverthless openra UI being only english. I do think its fair point already. (?)

IMHO, tackling #9712 "issue" could be driven separatelly/parallel to localization works (which needs far more manpower and time to lift) and will only support issue #10475 it in future. I dont see how it these two could collide or make obstacle for themselfs..
