### ISSUE TITLE
Clean up the filesystem code

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10717]
The virtual filesystem (VFS) code is/was a giant ball of technical debt, and cleaning it up will win us a lot of perf and feature improvements.  This ticket tracks the previous and future progress on the issue.

- [x] Un-global the FileSystem class. [#9853]
- [x] Streamline the package interface, moving the various mix-format workarounds from engine code into the mix file parser. [#10525, #10530, #10535, #10554]
- [x] Replace direct-filesystem lookups with VFS lookups. [#10687, #10703, #10704, #10705, #10706, #10713]
- [x] Reference maps via their packages instead of paths [#10786]
- [x] Restore "All packages" listing in the asset browser [#10716]
- [ ] Separate Map and MapPreview, and only load Map when absolutely necessary:
  - [x] Remove Map references from MapPreview [#10697]
  - [x] Remove automatic map format updating [#10701]
  - [x] Load map metadata without initializing throwaway maps. [#10768]
  - [x] Load map previews without initializing throwaway maps.
  - [x] Use MapPreviews in the server code.
    - [ ] Support querying the resource API directly, removing the need for dedicated servers to sync maps. [#10717]
  - [x] Use MapPreviews in the lobby code.
- [x] Implement `IReadOnlyFileSystem` interface, and replace use of `Game.ModData.ModFiles` with a passed `IReadOnlyFileSystem` object. [#10765]
- [x] Split sequence initialization out of RuleSet, and store the SequenceProvider on the individual Map and defaults in a `DefaultSequences` dictionary (keyed by tileset) on ModData.
- [x] Remove the lazy loading in Map.
- [x] Add support for "oramod" packages. [[pchote/oramod](https://github.com/pchote/OpenRA/commits/oramod)]

**Comment by pchote** [comment]
I have split #10993 into its own ticket because that turned out to be relatively separate from the other cleanups.
