### ISSUE TITLE
Additional useful lint tests

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11164]
- [ ] Actors with rendering traits but zero-sized bounds (ref #10830).
- [ ] Maps missing creeps/neutral player references or with inconsistent ally/enemy configuration for them (ref #11056).
- [ ] Map bound lint tests need to take terrain height into account. (ref #10686)

**Comment by reaperrr** [comment]
About the creeps/neutral enemy config, I think we shouldn't go overboard on this (read: throw a lint warning, but not an error), since iirc quite a few singleplayer maps throughout C&C games actually used such inconsistent configs (usually in cases where it didn't matter, like unarmed explosive barrels in RA), so this can easily happen when importing maps. There may even be a few missions that rely on that kind of setup.
In any case, I think we should only warn modders/mappers, but not enforce it.

**Comment by pchote** [comment]
Indeed.  We'll need to improve the lint plumbing a bit before we can add that, which is why I created this ticket instead of a PR.
