### ISSUE TITLE
WithAttackAnimation and WithMoveAnimation can't handle conditions

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11884]
Meaning neither are the traits upgradable themselves, nor can they handle multiple sprite bodies.
- [x] Make `WithAttackAnimation` capable of handling multiple sprite bodies. #13350
- [x] Make `WithAttackAnimation` conditional. #13350
- [x] Make `WithMoveAnimation` capable of handling multiple sprite bodies. #13294
- [ ] Make `WithMoveAnimation` conditional.

**Comment by reaperrr** [comment]
As mentioned in #12245, this is unfortunately not as simple as I had hoped, so removing from milestone.
