### ISSUE TITLE
Map Editor: Some Ideas

### ISSUE THREAD

**Issue by abc013** [OpenRA/OpenRA#12222]
I think with this features we could make the map editor more useable for map creators.
Here's @TheRaffy's and my wishlist:
- [ ] Add a window for the map's yaml (with save button) #2438
- [ ] If not created, create a button that adds it automatically (but when the lua is empty, delete it again)
- [ ] Add a window for the map's lua (if created, with save button)
  - [ ] Add a small window of Information about the current unit you are hovering over
  - [ ] Change owner
  - [ ] Change name
  - [ ] Change health #10818
- [ ] Save & play the map directly from editor
  - [ ]   Add the actors Number/Name to the Information window (ingame, f.e. `Actor107`).
- [ ] Copy a piece of a map and paste it on another map

**Comment by pchote** [comment]
Re the first two points: I certainly have no interest in writing or maintaining our own text IDE widget.  Better to leave that to real text editors.

Re the last point: The editor has supported copy/paste for ages.

**Comment by pchote** [comment]
The other points are covered by #4488 (which @Mailaender decided to close in favor of the less general #2053).

**Comment by abc013** [comment]
@pchote, i think you misunderstand the last point: I mean to copy a piece of a map to another map.

**Comment by abc013** [comment]
And, the point above the last one isn't mentioned in #4488.

**Comment by MustaphaTR** [comment]
About units, we also need ways to change Rotation, Turret Rotation and Subcell.

**Comment by reaperrr** [comment]
Point 3 with all sub-points would be quite useful indeed. About Point 1, it would help a lot if a few more things were editable directly in the map editor (Adding Players, Player stances & colors, for example).

@MustaphaTR Rotation is already possible via mouse wheel.

**Comment by Nineeva** [comment]
It would be amazing if the map editor did some of the script writing by allowing you to add players, change units rotation and health, I agree.  

Would also be great but, probably a lot more complex and therefore I appreciate less likely to be done to be able  

- to add queues to computer structures as an option on the map editor so they build units 
- be able to link those factories/barracks to way points so the computer sends waves at you.  
- add timers to the structures also so set how often they'll do this.  
- set it so the computer will rebuild a structure if destroyed, e.g. a setting on the building that will check if the computer can rebuild it and then attempt to build it if it can instead of leaving it destroyed.
- Or alternatively have a setting which you can tick for a player where they will attempt to rebuild any structure they loose if destroyed and harvesters when destroyed. Would make the computer a lot tougher in certain missions (maybe good for making a mission 'hard' on hard mod) (though maybe make sure you can turn it off on certain defensive structures?).
- Make a setting on structures/units can be critical to keep or destroy to win the mission.

All of this would reduce the amount of script writing to a minimum. Would also mean making the rest of the campaign would be so much faster.

Though like I said this is probably asking way too much, though one can dream :)

**Comment by Mailaender** [comment]
> I mean to copy a piece of a map to another map.

That is very hard to implement and a very unrealistic goal. Maybe http://www.mapeditor.org/ support could handle something like this in the future, but also that is just dreaming. https://github.com/bjorn/tiled/issues/387

**Comment by Mailaender** [comment]
> Add a window for the map's yaml (with save button) 

See also https://github.com/OpenRA/OpenRA/issues/2438 and https://github.com/OpenRA/OpenRA/issues/2827 which we rejected a long time ago.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/wiki/Map-scripting#ide-support for an OpenRA Lua editor. I solved it by #11686.

The other ideas can't be really discussed here as it is just too many at once. Please open individual tickets and do a quick search if a similar issue already exists.

**Comment by Mailaender** [comment]
> Add the actors Number/Name to the Information window (ingame, f.e. `Actor107`).

We already have https://github.com/OpenRA/OpenRA/pull/10078.
