### ISSUE TITLE
Add some performance-friendly TS maps

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12518]
Most of our currently included TS maps are closer to worst-case in terms of cliffs, bridges/water and size.

We should focus on the following smaller maps next.

FS:
- [x] Tiers of Sorrow (2): Very small, no water, no tunnels. #13941
- [x] They All Float (2): Quite small and no relevant water. #14576
- [ ] Dueling Islands (2): Small 2-player map, water should actually help performance once bridges/domains work better (due to lots of cells the pathfinder doesn't need to consider for most actors).

TS:
- [ ] Limited Access (4): Despite the name, performance should be ok due to medium size, max 4 players <s>and no bridges</s>. #14034
- [ ] Pit or Plateau (4): Similar reasoning to Limited Access.

**Comment by LipkeGu** [comment]
We should include the default map Grand Canyon also..

**Comment by Mailaender** [comment]
Pit or Plateau (4) features high bridges where we seem to be missing some parts:

```
104,0 unknown overlay 178
104,1 unknown overlay 178
105,0 unknown overlay 178
104,2 unknown overlay 178
106,0 unknown overlay 178
105,2 unknown overlay 178
106,1 unknown overlay 178
106,2 unknown overlay 178
```

Same for Limited Access (4) though I can't spot the high bridge gaps there

```
103,14 unknown overlay 178
103,15 unknown overlay 178
104,14 unknown overlay 178
103,16 unknown overlay 178
105,14 unknown overlay 178
104,16 unknown overlay 178
105,15 unknown overlay 178
105,16 unknown overlay 178
```

**Comment by reaperrr** [comment]
That's actually the VEINHOLEDUMMY overlay. If you look at the cell positions, it covers an area of 3x3 cells with a gap at the center cell, which is then occupied by the real veinhole.

No idea why our importer uses `0xBB` instead of `0xB2` for that. CRATE should be `0xB3`, too.

Note that the VEINHOLEDUMMY in the original most likely did not have any graphics, it probably just served to block veins and tiberium from spreading on these cells, or something like that.

**Comment by Mailaender** [comment]
@pchote told me that he got the real overlay IDs from FinalSun. For the RA2 bridges I noted there is a shift compared to the enumeration in the rules.ini as I guess some are skipped.

**Comment by reaperrr** [comment]
> @pchote told me that he got the real overlay IDs from FinalSun.

Ok, but if you take the [OverlayTypes] entry for VEINHOLEDUMMY, subtract 1 (since we start at 0) and and then subtract 2 for the missing entries 41 and 42, you arrive at 178, which coincides suspiciously well.

**Comment by Mailaender** [comment]
Okay, I filed https://github.com/OpenRA/OpenRA/pull/14033 as we don't need fake actors or fake overlays to block resource spreading. We can control resource growths under actors already with a boolean switch.

**Comment by Mailaender** [comment]
Dueling Islands (2), Limited Access (4) and Pit or Plateau (4) contain destructible cliffs. #13829

**Comment by fruestueck** [comment]
I am looking for a way to contribute and would start with making the map They All Float (2) if noone is working on it.

**Comment by penev92** [comment]
Currently the map editor is unable to handle terrain elevation, so making TS maps from scratch isn't really viable yet.
There is a way to convert TS maps to the OpenRA format - the Utility has a `--import-ts-map` command.

**Comment by fruestueck** [comment]
Sorry @Mailaender, didn't know the meaning of WIP when i started work on it.

**Comment by Mailaender** [comment]
I had trouble setting up the tunnels so thanks for taking over.

**Comment by fruestueck** [comment]
May i continue work on Pit or Plateau or any other map?

**Comment by Mailaender** [comment]
That depends on #13829 according to @pchote and adding support for destructible cliffs is not an easy challenge. See #14046 for an incomplete and finally aborted attempt.

**Comment by ABrandau** [comment]
Use these, you only need to rename a pair of bogus actors on each map.
https://resource.openra.net/maps/25993/
https://resource.openra.net/maps/25990/
https://resource.openra.net/maps/25968/
https://resource.openra.net/maps/25957/
https://resource.openra.net/maps/25956/
https://resource.openra.net/maps/26075/
https://resource.openra.net/maps/26032/
