### ISSUE TITLE
Projectiles and warheads in shipping mods are unoptimized

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12574]
We leave quite a bit of mid-battle performance on the table due to larger-than-necessary victim/blocker scan radii on many warheads and blockable projectiles.

- All TD and D2k weapons, and at least some RA and TS weapons, don't need to have actor scans on their effect warheads at all, because the warhead triggers on all ImpactTypes anyway.

- All `SpreadDamage` warheads, and `CreateEffect` warheads that don't trigger on all ImpactTypes, only need to scan up to the largest hit shape (OuterRadius).

- All blockable projectiles only need a blocker scan radius large enough to find blocking actors, so at least in D2k, TD and RA, they only need something like 768 WDist or less (most outer corner of wall pieces), more than halving the cost of scanning for blockers compared to the default of 1536 WDist. Currently, 50 RA flamethrower infantry firing at the same time cost up to >10ms mostly due to `Blockable: true` on my i5-2500, things are certainly worse on slower CPUs.

So to improve performance, following measures can (or rather should) be taken:

- [x] Automatically use the largest Shape.OuterRadius as victim scan radius for warheads, bouncing bullets and area beams #13236

- [x] Automatically use the largest Shape.OuterRadius of an actor with `IBlocksProjectilesInfo` as scan radius for blockable projectiles #13236

- [ ] Skip victim scan entirely on all `CreateEffect` warheads that don't need to scan for actors

**Comment by Mailaender** [comment]
How about a lint warning that detects these flaws so they don't get re-introduced when weapon rules are not observed by your watchful eyes like in thirdparty mods?

**Comment by reaperrr** [comment]
Good idea.

**Comment by reaperrr** [comment]
I have a working lint rule locally, but I can only repeat, that would be much easier to tweak once we use inheritance for all weapons.

**Comment by reaperrr** [comment]
In light of @pchote's comment on #12582, I'm beginning to wonder whether it would be a better approach to make the `SpreadDamageWarhead` and projectiles smarter, by refactoring `TargetExtraSearchRadius` into a `MinimumVictimScanRadius`. Instead of unconditionally adding that to Width/total spread radius, resulting in wasted resources, the warhead/projectile code would only add as much `WDist` as needed to reach that minimum scan radius. That way we'd only need to set a single value per mod instead of individual values per projectile/warhead, saving us and modders a ton of manual yaml labour and lint rule complexity.
On top of that, we could make the property name consistent (`CreateEffectWarhead` would no longer need to be a special case without that `Extra` in the property name).

Actually, makes way too much sense to not go down that route, but pinging @pchote just in case I'm overlooking something.

**Comment by pchote** [comment]
We could in principle automate the extra distance calculation here too.  Hook `IRulesetLoaded` and then enumerate all (&rarr; all relevant) actors and take the maximum hit shape radius at load time.

**Comment by 7heSAMA** [comment]
I would like to take on this issue along with #12582 and #11848 as a combined fix.

**Comment by reaperrr** [comment]
@7heSAMA Sure :) 
I haven't gotten around to updating #12609 and probably wouldn't for a while longer, so I wouldn't mind if someone else took over.
I suggest you take a look at that PR (if you haven't already), some of the code or at least the comments might be of use.

**Comment by GraionDilach** [comment]
@7heSAMA Please also read the discussion of https://github.com/OpenRA/OpenRA/pull/11624#issuecomment-238219913 and followups. I'd be happy to see that issue resolved myself as well.

**Comment by 7heSAMA** [comment]
@GraionDilach Refactoring ImpactTypes seems like a good first step for this and your PR. 
@reaperrr, I will look at that one as well. It doesn't look like you modified the ImpactTypes there, any tips or a PR to reference?

**Comment by reaperrr** [comment]
@7heSAMA That was the primary missing part, basically.

As for tips, well the important bits are (as far as I'm aware):
- Valid/InvalidTargetTypes (inherited from parent `Warhead`) need to be taken into consideration, to fix issues like explosion displaying on submerged RA subs
- the `IsWater` check should be removed in favor of either using the above, or a separate `Valid/InvalidTerrainTargetTypes` check (I remember running into difficulties with the former approach, but I don't remember the details, unfortunately).
- the hardcoded `airMargin` of 128 WDist should be replaced with something better. My idea would have been to add a `ValidMinimumAltitude` and a `ValidMaximumAltitude`, the former with a default of 0, the latter with a default of "unlimited unless not 0". Then modders would have to set things up like this: ground-/water-only effect warheads would need to define `ValidMaximumAltitude: 128`, while the air-only warhead(s) would define a `ValidMinimumAltitude: 129`, for example.

**Comment by GraionDilach** [comment]
Terrains can multiple have TargetTypes, so I don't see the reason behind a separate list for them. I'd suggest https://github.com/GraionDilach/OpenRA.Mods.AS/blob/master/Traits/Warheads/WarheadAS.cs as a reference, because it's my solution to this issue - albeit I have a hardcoded hack which is why I didn't PRed it - and it hasn't failed me on all 5 of my custom warheads so far (with #11624's final code being among them).

**Comment by reaperrr** [comment]
@Kris-with-a-K Sorry, but since my old PR from March was basically about 80% there already and I needed it quickly to avoid work-arounds in #13196 and its follow-ups, I went ahead and updated it, so the bulk of this issue will be adressed by that: #13236

That being said, #12582 / point 3) of this issue and #11848 are not adressed by my PR, so if you focus on those there shouldn't be much - if any - overlapping between our PRs.

**Comment by Kris-with-a-K** [comment]
Ok @reaperrr, sounds good. Again, sorry I haven't been able to chip in, just really busy.
