### ISSUE TITLE
Merge Mods.RA and Mods.TS into Mods.Cnc

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12659]
- [x] Merge Mods.RA into Mods.Cnc #12757
- [x] Merge Mods.TS into Mods.Cnc #12678
- [ ] Move Mods.Cnc.dll to `mods/common` #12763

As discussed on IRC, #12554 and #12617. This should be a relatively easy task and happen before the next release.

D2k should stay separate.

**Comment by Mailaender** [comment]
How about calling it `Mods.CnC`? :bike:

**Comment by reaperrr** [comment]
> How about calling it Mods.CnC?

I'd be fine with that, but I don't know how much that might affect the git history, I think we should only do that if it doesn't break it (or if @pchote's mod support changes break git history anyway).

**Comment by GraionDilach** [comment]
Probably it would, considering that git was written with a case-sensitive OS in mind - ohio, Linux.

**Comment by pchote** [comment]
That might cause another situation like #7754 (comments).

**Comment by reaperrr** [comment]
> That might cause another situation like #7754 (comments).

Just to be sure, do you mean renaming to CnC or merging the dlls in general?

**Comment by pchote** [comment]
Renaming to CnC.  I'm all for merging the dlls!

**Comment by pchote** [comment]
@reaperrr: Is merging the RA dll on your immediate todo list?

**Comment by reaperrr** [comment]
Yes. In fact, the only reason why I've been waiting a little is #12681.

**Comment by pchote** [comment]
It would be better to get this out of the way and then rebase #12681.  This one is blocking the release and other changes, while that one is less critical.

**Comment by reaperrr** [comment]
Ok, but I'll wait until #12697 is merged to avoid a rebase.

**Comment by GraionDilach** [comment]
As part of that merge though, could ParatroopersPower end up in Common instead? It's weird that the most common paradropping method is is currently RA atm, while the ParaDrop trait itself is part of Common due to crate paradrops and the paradrop factory trait.
