### ISSUE TITLE
Move remaining Westwood file formats to Mods.Cnc

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12775]
Just VQA left:

- [ ] `Scripting\Media.cs` calls `VqaReader` directly
- [ ] `Scripting\Global\MediaGlobal.cs` calls `VqaReader` directly
- [ ] `AssetBrowserLogic` needs `VqaPlayerWidget`, which also calls `VqaReader`
- [ ] `MissionBrowserLogic` needs `VqaPlayerWidget`, which also calls `VqaReader`

Note: `ShpTS` and `RLEZerosCompression` should remain in `Common` as discussed on IRC, as ShpTS has the best community tool support (and its `RLEZerosCompression` is non-proprietary).
