### ISSUE TITLE
Resupply refactor roadmap

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16403]
To make it a bit easier to get an overview in which order PRs should be reviewed/merged and what follow-ups are in the pipeline.
Some of this overlaps with #16338.

- [ ] Merge Rearm and Repair activities into single Resupply activity (#16352)
- [ ] Split a central `ResupplyManager` from `Repairable` (locally pretty much done)
- [ ] Refactor `Reservable` into `Dock`, with various improvements including docking offset (locally pretty much done)
- [ ] Refactor `ResupplyManager` activity queueing/actor enter logic (not done yet)
- [ ] Possibly move all of `Aircraft`'s "Resupply" order handling to `ResupplyManager`

**Comment by reaperrr** [comment]
Moved to Next+1. I would like to get at least the first two or three points in before the next playtest anyway, but completion of this roadmap shouldn't be a blocker for next release.
