### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2824]
After the discussion at http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=15948 I started to hack on OpenRA l10n. There are some quite a lot of fan translations of OpenRA and Red Alert on the net. I collected my findings at https://github.com/OpenRA/OpenRA/wiki/Translation

Some sub-tasks:
- [x] Add a language selector to settings GUI (trivial)
- [x] "HOLD", "READY" are translatable via YAML #2526
- [x] "Requires:" and CustomPrerequisites are translatable via YAML #2526
- [ ] Voice/Icon gamefile downloader GUI (optional)
- [ ] Auto-adjust layout/size of Widges on text size
- [ ] [textless icons](http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&t=15353) nearly finished, we could then print the unit names live on them without photo-shopping or just go for the tooltips only

Some strings are hard-coded and not exposed to YAML editing (yet):
- [ ] "Primary" (check if this is still an SHP)
- [x] Tabs mouseover ("Buildings", "Defense", "Infrantry", ...)
- [x] DropDownBox contents
- [x] Text in *LoadScreen, *InstallLogic, ...
- [ ] Singleplayer objectives

**Comment by Mailaender** [comment]
After https://github.com/OpenRA/OpenRA/pull/8675 I might declare this whole attempt failed for the momemnt. We probably need a new `strings.yaml` to fetch dialog texts from for the hard-coded strings in widget (logic) and dialogs. It needs to be a dictionary that can also be translated into multiple languages. However that also won't account for strings in rules and mission map yaml or even Lua. Also without using a standardized toolkit such as GetText or .NET resource files we probably also need to create our own tooling. Will close this here as I feel this needs some rethinking from scratch.

**Comment by pchote** [comment]
Do we have a generic translation tracking ticket to replace this one?

**Comment by Mailaender** [comment]
No, not yet.

**Comment by abcdefg30** [comment]
I reopened #8968 to replace this ticket.

**Comment by pchote** [comment]
Superseded by #10475.
