### ISSUE TITLE
Tiberian Sun / Red Alert 2 mod [$1,637]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3363]
This is a tracking bug for the engine changes that are required to support Tiberian Sun and Red Alert 2 on the OpenRA engine.  The main goal of these efforts will be shipping our WIP TS mod in the main OpenRA download.

The main requirements are:
- [x] Voxels. [#3274]
- [x] Orthographic tileset support. [#5350]
- [x] MixFile package format changes [#3227]
- [x] SHP sprite format changes. [#3193, #4185]
- [x] Sequence changes ordered sprites. [#3333, #3571]
- [x] VQA video file format changes. [#3226]
- [x] Heightmap support for shroud [#8781]

**Comment by Mailaender** [comment]
We are done here. There is now a separate list for the required game-related traits for Tiberian Sun at https://github.com/OpenRA/OpenRA/issues/7874. Red Alert 2 is work in progress at https://github.com/Phrohdoh/oramod-ra2.

**Comment by pchote** [comment]
We are now very close to achieving this goal (engine support for the core TS/RA2 mod requirements), but we aren't quite there yet.  The remaining blocker is heightmap support for the shroud, which I have mostly implemented already and plan to open a PR for within the next couple of weeks or so.

**Comment by Mailaender** [comment]
Also added the aircraft height glitch to this list.

**Comment by pchote** [comment]
#8781 has now been merged, which was our last major engine feature needed for TS.  There are two followup PRs waiting on review that clean up a few leftover bits, but this is otherwise done.  I will close this once that final followup is merged.

The remaining issues are either cosmetic (e.g. z-buffer sorting, terrain lighting) or are mod-level features (e.g. aircraft bugs, subterranean movement, gates, etc, etc) rather than core engine changes.

**Comment by pchote** [comment]
https://www.youtube.com/watch?v=WoZoQILTaGk shows off where we have reached with our engine and mod support for TS.

**Comment by UberWaffe** [comment]
Is there agreement internally between the developers as to how the bounty claim will work?

I see some random person "llSourcell" claiming to have worked on this for the past 9 months, and I am very sure they never actually did. So I'm just asking so that the bounty is not fraudulently claimed.

**Comment by pchote** [comment]
I have done the vast majority of the work, and will claim the bounty.  I will then redistribute some of that to other TS-related tickets.

**Comment by grasmanek94** [comment]
So.. this is done? Are we going to see RA2/TS soon? :)

**Comment by Phrohdoh** [comment]
This ticket has been closed but that does not mean TS is ready to ship.

> This is a tracking bug for the engine changes that are required to support Tiberian Sun

So this is only in regards to engine support, not completion of TS as a stable(-ish) mod, sorry.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/7874 or any tickets with the `Tiberian Sun` label for the current TODO list and https://github.com/OpenRA/ra2/issues for Red Alert 2 related tasks and problems.
