### ISSUE TITLE
MapFormat increment checklist

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#4251]
- [ ] Fix up the map smudge yaml layout. `cr1 60,79 0:` is inconsistent in that it doesn't follow the idiomatic yaml tree structure that we use for everything else.
- [ ] Let all files in map archives contribute to the map uid, instead of just map.yaml and map.bin. This lets maps with edited Lua code have different uids.
- [ ] Allow rules to be in their own files in addition to map.yaml.

**Comment by atlimit8** [comment]
Just noting that if #10255 is merged, then its palettes should be de-duplicated.

**Comment by pchote** [comment]
The generic tooltip stuff from #6613 too.

**Comment by pchote** [comment]
I'd like to get this into the next release for two reasons:

1. It ties in well with (and is now easy to implement thanks to) my ongoing mission to tidy up our map loading / filesystem code.
2. Removing the map auto-update and changing the map dir is going to be a significant PITA to our players.  I'd like to get all of our format changes out of the way at once, instead of dragging out enforced upgrades over the next two or three releases.

**Comment by pchote** [comment]
I have implemented these three changes in my [map-format-nine](https://github.com/pchote/OpenRA/tree/map-format-nine) branch, which will turn into a PR once the prerequisites have been merged.
