### ISSUE TITLE
Renamings and Reorganisation

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#5274]
A collection from stuff suggested in IRC. These could be done once the pull request queue is a little less crowded https://github.com/OpenRA/OpenRA/issues/5263.

- [x] OpenRA.Support.Random clashes with System.Random https://github.com/OpenRA/OpenRA/pull/5359/
- [x] WRange → WDist ~~https://github.com/OpenRA/OpenRA/pull/4701~~ https://github.com/OpenRA/OpenRA/pull/8667
- [ ] OpenRA.Renderer.* is actually more like OpenRA.Platform.* because it is graphics + input and could also include OpenRA.Sound which is currently in OpenRA.Game so we save linking to SDL2 there. ~~https://github.com/OpenRA/OpenRA/issues/5787~~ ~~https://github.com/OpenRA/OpenRA/pull/8538~~ https://github.com/OpenRA/OpenRA/pull/8632
- [x] Many traits in OpenRA.Mods.RA should actually be in OpenRA.Mods.Common as they are shared in all three mods. Same goes for system rules every mod needs or shared chrome definitions which could also be moved to `mods/common/` for clarity. ~~https://github.com/OpenRA/OpenRA/pull/5321~~ https://github.com/OpenRA/OpenRA/pull/6511
- [x] Don't call factions countries or races. https://github.com/OpenRA/OpenRA/issues/7552
