### ISSUE TITLE
Tiberian Sun / RA2 tileset support [$130]

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#5350]
This is a tracking bug for implementing the isometric heightmapped terrain used in TS and RA2.  This is the main prerequisite of our TS mod (#3363).

Requirements (roughly in the order they will need to be completed):

- [x] Introduce a new self-consistent 3d coordinate system. [#2887, #2917, #3433, #3434, #3531, #3583, #3586, #3592, #3861, #3886, #3887, #4371, plus probably others]
- [x] Unhardcode the infantry sub-cells to support 3 instead of 5 and adapt the perspective [#6100]
- [x] Add support for the tmp(TS) terrain tiles.
  - [x] Update the terrain renderer to support additional sprite types. [#4185]
  - [x] Add support for flat isometric tiles. [#4391]
  - [x] Add support for loading embedded overlay artwork (cliffs, slopes). [#6855]
  - [x] Add support for TS/RA2 style terrain variants. [#7757]
  - [x] Support parsing the depth data as additional sprite frames. [[pchote:ts-tileset-depth](https://github.com/pchote/OpenRA/tree/ts-tileset-depth)]
- [x] Add support for orthographic (isometric) tile renderering.
  - [x] Support rectangular tiles with perspective. [#4391]
  - [x] Generalize the (currently hardcoded) relationship between cell and world coordinates.
[#5629, #5757, #5758]
  - [x] Introduce isometric coordinate calculations. [#5778]
- [x] Add support for heightmaps and slope tiles.
  - [x] Extend Tileset format with fields for slope type and LAT relationships. [#6855]
  - [x] Extend Map format with a heightmap block. [#6901]
  - [x] Update cell -> world coordinate conversion to use the heightmap data. [#6901]
- [x] Write a TS/RA2 tileset.ini converter [#6708].
- [x] Write a new map editor that can render and place isometric tiles. [#4496]

**Comment by LipkeGu** [comment]
maybe we should use "[pchote:ingame-map-editor] / [Mailaender:ingame-map-editor] because both of them are working on to that point ...

**Comment by pchote** [comment]
We are now very close to completing this goal.  The main remaining task is TS-style tile variants (using separate sprites for each template version), which is one of the next items on my TS-todo list.

**Comment by obrakmann** [comment]
not quite closed yet, one bullet point remains.

**Comment by pchote** [comment]
The map editor is only tenuously related - all the format support is now included, but the editor is there because it shows off / uses it.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/8065 has been merged.
