### ISSUE TITLE
Replace Rank and Tags and make more use of WithDecoration

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7551]
Basically what @Phrohdoh tried to do for #7466 (as discussed on IRC).
This can be extended and be used for:
 - [x] The spy insignia (#7466)
 - [ ] Unit stance decoration (#3437)
 - [x] Unit rank (#8300)
 - [ ] Adding a faction logo to MCVs (since most games use the same MCVs for all factions, a logo to distinguish what MCV is the one you are looking at might be nice). Same for ConYards.
 - [x] "Unit waiting for carryall", as seen in the original Dune 2000
 - [ ] Sum of all `IDamageModifier`s (shield if < 100% damage, for instance)
 - [ ] Primary Building indicator
 - [ ] "Hero unit" decoration (be it a star, like Mental Omega, or a skull like Tiberium wars), again mentioned in #7466
 - [ ] Fake building indicator

**Comment by penev92** [comment]
>[14:20] <+pchote> the current rank implementation is horrible
[14:20] <+pchote> an artefact from ancient days
[14:20] <+pchote> the first step will be to fix that
[14:21] <+pchote> this probably ties into the (also horrible) pips and tags code
[14:21] < penev> afaik that's what Phrohdoh started with
[14:21] <+pchote> they are all basically the same, except they get drawn in different places

**Comment by Phrohdoh** [comment]
My attempt compiled and ran fine and I threw some debugs in for good measure but nothing 'new' was ever drawn to screen.

:+1: for someone telling me what I was doing wrong or someone doing it properly.

**Comment by Phrohdoh** [comment]
Added ` Sum of all IDamageModifiers (shield if < 100% damage, for instance)` to list of use-cases.

**Comment by penev92** [comment]
Adding the Primary Building "star" tag.

**Comment by penev92** [comment]
Added fake buildings.

**Comment by pchote** [comment]
Refactoring of our existing decorations is complete, and the other ones are probably out of scope.  Closing as fixed.
