### ISSUE TITLE
New D2k maps

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7697]
There are quite few distributed maps for the D2k mod. Not too many on the resource site, either, and honestly, searching for maps for a specific mod there is still impossible.
So with OpenRA now having a map importer for D2k maps, I suggest we boost the arsenal a bit for the next playtest (then some more for the release).
How about we start by importing some of the original skirmish maps?
I've generated previews of all 36 original skirmish maps and uploaded an archive [here](https://www.dropbox.com/s/qcj3ktwmmadepl5/Showcase.rar?dl=0). ~~The file names tell you how many players the map has.~~
I'd like to hear opinions about the maps and suggestions which to start with.

Note: some maps have visual glitches because I generated all previews using the same tileset, but they should still give you a pretty good idea of the terrain layout.

Original official skirmish maps:
- [ ] 2PLAY1 - preview pending
- [ ] 2PLAY2 - preview pending
- [ ] 2PLAY3 - preview pending
- [ ] 2PLAY4 - preview pending
- [ ] 2PLAY5 - preview pending
- [ ] 2PLAY6 - preview pending
- [ ] 2PLAY7 - preview pending
- [ ] 2PLAY8 - preview pending
- [ ] 2PLAY9 - preview pending; Note: import results in broken tiles due to missing tiles from the BLOXBGBS tileset
- [ ] 2PLAY10 - preview pending
- [ ] 2PLAY11 - preview pending
- [ ] 2PLAY12 - [preview](http://i.imgur.com/jToXtuV.jpg); [.oramap file](https://www.dropbox.com/s/it2xwrshjji8fko/2PLAY12.oramap?dl=0); Note: The map has 8 starting locations, so I've left all of them. I reduced the wormspawners though, to account for our more serious worms
- [ ] 2PLAY13 - preview pending; Note: import results in broken tiles due to issues with out version of the BLOXXMAS tileset and/or the importer's interaction with it
- [ ] 2PLAY14 - preview pending; Note: import results in broken tiles due to missing tiles from the BLOXBGBS tileset
- [ ] 3PLAY1 - preview pending
- [ ] 4PLAY1 - preview pending
- [ ] 4PLAY2 - preview pending
- [ ] 4PLAY3 - preview pending
- [ ] 4PLAY4 - preview pending
- [ ] 4PLAY5 - preview pending
- [ ] 4PLAY6 - preview pending
- [ ] 4PLAY7 - preview pending
- [ ] 4PLAY8 - preview pending
- [ ] 4PLAY9 - preview pending
- [ ] 4PLAY10 - preview pending
- [ ] 6PLAY1 - preview pending
- [ ] 6PLAY2 - preview pending
- [ ] 6PLAY3 - preview pending
- [ ] 6PLAY4 - preview pending
- [ ] 6PLAY5 - preview pending
- [ ] 8PLAY1 - preview pending
- [ ] 8PLAY2 - preview pending
- [ ] 8PLAY3 - preview pending
- [ ] 8PLAY4 - preview pending
- [ ] 8PLAY5 - preview pending
- [ ] 8PLAY6 - preview pending
##

**Comment by Mailaender** [comment]
Sorry, I doubt many will download a RAR file, look at 36 maps and then give useful feedback. I suggest you upload them at http://resource.openra.net/ and let the community pick good candidates by popularity vote.

**Comment by penev92** [comment]
Yeah, unfortunately that's not happening.
If anyone wants to check the original maps and then say which he likes/import them himself, he's free to do it.
I can't go through 36 maps, try 7 tilesets for each one, manually check each for broken tiles to determine which the correct tileset is and then import with that one, so that I can eventually upload those maps to the resource site to be forgotten, OR file 36 PRs and hope that a couple will be accepted.

**Comment by obrakmann** [comment]
FWIW, I think it would be enough if those maps were uploaded to r.o.n. at some point. There's hoping that we get the resource site integration in the map chooser sometime this year. We should be able to significantly cut down on the number of maps we ship overall.

**Comment by penev92** [comment]
OK, so I decided to give it a try with 2-3 maps as a start and ran into unexpected problems - missing tiles. I managed to do only 1 map so far - 2play12.
I added a preview, link to the oramap file and some comments.

**Comment by OmegaBolt** [comment]
Interesting ones for me: 2play7, 2play8, 2play11, 2play13, 2play14, 3play1, 4play1, 4play3, 4play4, 4play10, 6play1, 6play4, 8play1

**Comment by MustaphaTR** [comment]
4 maps are added for the next version.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/issues/7697.
