### ISSUE TITLE
Add engine support for features required by a MechCommander-based RTS mod

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7718]
Have always wanted to make one, as I see massive fun-potential in this. 
To my knowledge MechCommander (Gold) is freeware (though not open-source like MechCommander 2, unfortunately), so there shouldn't be any legal issues.

There are several features and fixes required to make this good and keep the amount of work in check (especially on the graphics side). This issue is supposed to keep track of the individual requirements.
- [x] #7717 Make actor height (and Z height for targeting) customisable
- [x] #7716 Add support for SSI shp version 1.10 (assembly outside of OpenRA)
- [ ] #9268 Add support for directional armor
- [x] #7666 Support for using individual files for each frame of a sequence
- [x] #6631 Add SplitFacings option to various Render traits
- [x] #6465 Minor offset issues with barrels, muzzle flashes...
- [x] #6247 Issue with order click area (diamond-shaped cells)
- [x] #3736 Missiles move towards ground before moving towards target
- [x] #9677 Facing reflection/mirroring (required for #3274 as well)
- [x] #7675 Raycast collision detection for projectiles

**Comment by ivicok** [comment]
It's a great idea, though I see MC as highly different in many aspects not related merely to graphics:

- pre-mission loadout: choice of starting units, their equipment, pilots;
- critical hits: random effects caused by damage;
- accuracy: based not only on weapon spread, but also by target's movement;
- multiple hit zones: torso, head, arms, legs...related to critical hits;
- salvaging: shouldbe also related to criticals;
- movement modes: run, walk, jump;

some of these things can be made in the state of the engine, but not the menus, in-game loadouts and criticals... or am I wrong?

**Comment by reaperrr** [comment]
@ivicok The idea is not to recreate every aspect from MechCommander, only to implement certain fixes and features to allow making a C&C-style RTS with MechCommander mechs and vehicles. And at least in theory, everything you mentioned could be implemented, it's just a matter of getting people with enough time and skill to actually do it.

**Comment by yaaaaa** [comment]
Wow, where I can looking for the progress of this mod?
