### ISSUE TITLE
Finalize the D2k mod

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7751]
Despite the amount of work so many people put into D2k over the past 6 months, the mod is still a long way from finished.
I'm opening this to keep track of everything that remains to be done. There are several issues open, containing bits and pieces, and there are things that aren't mentioned in any issue yet.
 - **Carryall:**
  - [ ] Transport damaged vehicles to the repair pad

- **Sandworms:**
 - [ ] Implement the thumper infantry (#7130)

- **Implement original Dune 2000 balance:**
  - [ ] Add structure upgrades and fix prerequisites (Issue: #3211; PR: #7597)
  - [ ] Rename actors/weapons/effects to match the originals (#7558)
  - [ ] Import original actor/weapon statistics (probably a follow-up of #7558)
  - [ ] Fix support powers to match the original

- **AI:**
 - [ ] Make the AI aware of worms (#7048)
 - [ ] Make the AI aware of and able to use concrete (#5784)
 - [ ] Make the AI aware of and able to use thumpers
 - [ ] Make the AI aware of and able to use structure upgrades
 - [ ] Make the AI capable of dealing with the original starport behavior
 - [ ] Make the AI capable of dealing with the original spiceblooms behavior

- **Utility:**
 - [ ] Improve map importer handling of "missing" tiles
 - [ ] Implement at least partial MIS file reading (#4280)

- **Other:**
 - [ ] Starport - implement the proper behavior (Issue: #7055; PR: #7468 + follow-ups)
 - [ ] Spiceblooms (#4462)
 - [ ] YAML polish (#7274)

**Comment by OmegaBolt** [comment]
Here is the latest balance effort: https://github.com/OmegaBolt/OpenRA/tree/d2k-bal

"Fix support powers to match the original" could be more specific such as mentioning the need for #6976 and also adding cluster weapon logic for the Death Hand (#7773 or #7509 in regards to airburst).

Devastator self destruct ability (apparently it requires some logic stuff first). I believe actually in the original it uses a cluster weapon too. Rather than simply damaging all units around it, the effect hits random units in any adjacent cell, but I'll need to test this further to confirm.

**Comment by GraionDilach** [comment]
After I'll get AS up'n'running - which is the main reason why I'm off the radar sorry - I'll prolly look at ProductionPower for this and TS HunterSeekers.

**Comment by MicroJOo** [comment]
hate to say that @penev92 ...  but you should add :

- [ ] Polish Sandworms 

cause they still have no proper sandanimation when moving ... just the lightnings

**Comment by penev92** [comment]
>Note: There are several other issues that are not mentioned here because they are either visual or audio polish, or not important features like those mentioned above.

But if people want, I can try to make an all-encompasing list, with all the little polishing things.
Most of them have their own issues though. The worms do have one open.

**Comment by MicroJOo** [comment]
im just saying ...i think even the visual polishes do count to call it "final" ... 
im sure "fans" do care about details ...

**Comment by pchote** [comment]
This is a meta ticket, so it would be nice if this could link to all the polish sub tickets.

**Comment by Unit158** [comment]
We also need the timed spawning from the palace

**Comment by OmegaBolt** [comment]
Which I already mentioned (#6976).

Fix the Dune 2000 shroud so it is not see-through. I had a go at this here (https://github.com/OmegaBolt/OpenRA/tree/d2kshroud) a while go but I think pchote wanted to do some actual code changes.

**Comment by penev92** [comment]
Updated with the suggestions above.

**Comment by MicroJOo** [comment]
update please , "Finish D2K worm implementation" # 10385

**Comment by MustaphaTR** [comment]
Devastator self destruct is added. And there are no more missing tiles left.

**Comment by penev92** [comment]
Ticked the Devastator and missing tiles checkboxes. The sandworm was ticked.

**Comment by penev92** [comment]
Reworked the Starport varying prices entry.
Added entries for original concrete behaviour (#5931) and Sardaukar crushing (#4476).

**Comment by CH4Code** [comment]
Utility: Map Importer - handling of missing tiles was completed a while ago: #13297 and #12784.

**Comment by penev92** [comment]
Damn it this is the third time I check that checkbox!

**Comment by abcdefg30** [comment]
Added a note to check the tileset definitions. Example reported on Discord:
![](https://cdn.discordapp.com/attachments/279290580201373696/764913664410910770/issues.png)

**Comment by Kalyxt** [comment]
In original d2k, units came out from primary building only. If you have 5 tank factories, each in the different base, you could select primary building and supply units where you need them (they have shorter build time also).  In OpenRa, they came out from every tank factory if you start to produce more than one unit at the time.

This could be really frustrating as units have to came across longer distances as you are expanding through map.

**Comment by dragunoff** [comment]
@Kalyxt The d2k mod in OpenRA uses a classic single production queue - meaning that units come out of a single facility and multiple facilities decrease the build time. So this is the same behavior as the original cnc games. And you can set a production facility as primary by clicking it (same way as in original games). 

There is however a scenarion where units would come out of a different factory - that happens when something is blocking the factory's exit. It can happen easily when you enable the cheat for instant production. Or it can happen when units are clumped in front of the factory. To avoid the second case make sure you place a rally point for the factory so that units move away from the exit. There is code that bumps them automatically but in some cases it doesn't succeed and the new unit comes out of a different factory.
![OpenRA-2020-11-16T101451104Z](https://user-images.githubusercontent.com/1355810/99241312-5e2f3900-2806-11eb-8fc6-d2d2a6009d17.png)

**Comment by Porenutak** [comment]
Dont know if this is know (its not included in the list):
Sonic tank  beam travels always at max. range. No matter the enemy distance. 

![sonicShoot_optimized](https://user-images.githubusercontent.com/100044015/173184649-a347e8d5-a67d-486a-a93b-688b0a8345bc.gif)
