### ISSUE TITLE
Add TS features required for a full remake

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7874]
Features that need to be added for a (nearly) complete remake:
- [x] Z-Buffer support for the renderer #7520
- [x] Split shadow sprites #3571
- [x] Installation from CD #3883 and asset download #3888 including music #8161 
- [x] Installation of Firestorm assets from CD and download. #12429
- [x] Turrets attaching to walls #4970
- [x] Radar dishes that stop spinning on low power #5138
- [x] Remappable resources #5155
- [x] Idle overlay sprite support #3681
- [x] Overlays that only animate with active production #5134
- [x] Construction yard crane overlay #5124
- [x] Voxel harvester unload animation #5797
- [x] Harvesting sprite animations #3458, #7204
- [x] Building plugins (components) #7812
- [x] Resource splattering for destroyed units containing Tiberium #2346
- [x] Hovering #7033
- [x] EMP
  - [x] stun actors #6653
  - [x] overlay animation #8581
  - [x] but as a super weapon #7349
- [x] AlphaImage support #7853
- [ ] Ion storms
  - [x] Lighting [#7863]
  - [ ] Disabling actors
  - [x] Lightning #7872
- [x] AmbientSound #7871
- [x] Individual weapon factory door overlays #7862
- [ ] Support for per-height-level ambient lighting [#3605]
- [x] Gates #9981
- [ ] Subterranean movement (and detection of it) [#7777]
- [x] Make actor height customisable [#7717]
- [x] draw stealthed actors semi-translucent instead of in shadow color #8996
- [x] Carryalls to manually pick up and release units #8954
- [ ] Laser Fence logic #6072, #10790
- [ ] Firestorm generator logic and effects #10789
- [x] Voxel image changing when moving over water terrain type (for amphibious APC) #7981
- [ ] Particle effect system (damage/wielding sparks, railgun, gas clouds, smoke)
- [x] WithChargeOverlay (for Obelisk) #7982
- [x] Tunnel system [#6410]
- [ ] High Bridges [#8917]
- [ ] Refactor missiles [#7509]
  - [x] Airburst for missiles
  - [ ] Weapon spawning from airburst
  - [x] Projectile (missile) acceleration
  - [x] Customisable cruise altitude for missiles (and support for arcing flight curve) [#3736]
- [ ] Add support for voxel projectiles [#7673]
- [ ] Add support for voxel debris
- [x] Improved LaserZap (more fine-grained "facings" for start/end of lines) #8009
- [ ] Damage at current projectile coordinate during flight (for flamethrower)
- [x] Line damage (for sonic zap and rail guns) [#4458]
- [ ] "Rocker" property for warheads (make voxels 'rock' on impact)
- [ ] Deforming terrain by weapons
- [ ] Meteors
- [ ] Small visceroids fusing to a single large one #10791
- [ ] Drop Pods
- [ ] Hunter-Seeker logic (release as support power not individual units) #6478
- [ ] Waypoints #10470
- [ ] Ice cracking logic [#8918]
- [ ] Veinhole logic
  - [ ] Vein rendering #9688
  - [ ] Veins recede after veinhole destroyed #9689
  - [x] Veins should damage vehicles and buildings #9690
  - [ ] Gas projectile when attacked #9691.
- [ ] Chemical missiles [#7775]
- [ ] Cluster missiles [#7773]
- [ ] Component Towers/Gates can be placed on walls, replacing them #12088
- [ ] Actor acceleration/deceleration, as well as speed modifiers for moving up/down a slope
- [ ] More control over some AI aspects (squad composition, probability of squad type, etc.)
- [ ] Significantly improved Pathfinding performance
- [ ] Train logic (movement restricted to tracks) #2652
- [ ] Tiberium explosion chain reaction
- [ ] Forest fires (if tree burns, nearby trees can catch fire) #6403
- [x] Bouncy bullets (disc thrower)
- [x] Jumpjets (might be doable with existing logic)
- [x] Armory (inf enters, returns as veteran, might be doable with existing logic) #8210
- [x] Hospital (hurt inf goes in, exits healed) #10363
- [ ] Ion cannon ripple effect
- [x] Cyborg logic (permanently lose legs when brought to low health once) #8261
- [ ] configurable tilt/roll/pitch angle for voxel aircraft
- [ ] Tiberium fiends logic (run to Tiberium and lay down to heal)
- [ ] auto-deploy attacks (artillery, tick tanks)
- [x] Wakes #5858
- [ ] destructible cliffs
- [ ] `NoMovingFire=yes` support #2327
- [x] Harvester docking overlay sprite #10364
- [ ] Scripted map bound changes #8221 etc.
- [ ] Waterfall terrain animations #6433
- [ ] Concrete plates / pavement #7878
- [x] Differentiate between Cabal/EVA voices and Nod/GDI icons #8799
- [ ] Vehicle tilting on slopes and bumps #9012
- [x] Right-click switch scrolling #9518
- [x] Eject cargo on destruction #3768

This list is probably far from complete.
##

**Comment by Phrohdoh** [comment]
What is `Manually controllable Carryalls`? The carryall aircraft in TS *can* be controlled by the player.

**Comment by Mailaender** [comment]
> What is `Manually controllable Carryalls`? The carryall aircraft in TS *can* be controlled by the player.

Basically the same as https://github.com/OpenRA/OpenRA/issues/4312 but for Tiberian Sun as opposed to the automatic carryall system we have for Dune 2000. [#6780, #7033, #7167]

**Comment by Phrohdoh** [comment]
Then :-1: for that which is a pretty fundamental change.

**Comment by Mailaender** [comment]
Renamed it to `Dropships that manually pick up and release units (Carryalls)`. Hope you get it now.

**Comment by reaperrr** [comment]
> `Firestorm generator logic and effects` isn't needed for TS, it is a feature of FS.

Please check the facts first, this is simply completely wrong.

**Comment by reaperrr** [comment]
> Then :-1: for that which is a pretty fundamental change.

I don't get what your problem is. In original TS the Carryall (not Dropship) was controllable and could pick up vehicles you could then transport anywhere on the map. Why :-1: a feature original TS had?

**Comment by reaperrr** [comment]
@Mailaender: Changed back to Carryalls, Dropships were not controllable (they appeared in single-player only, actually).

**Comment by Phrohdoh** [comment]
Ah sorry I read Matt's comment wrong. I thought he meant using the Carryalls in the same way that D2k does.

**Comment by gangster-ppm** [comment]
I would preferred a manually controlled carryalls but with full auto mode if they were "docked" at refinery. :) also I d like to add Cliff shadow feature in the list.

**Comment by penev92** [comment]
`Installation of Firestorm assets from CD and download.`
I don't think this has a place here.

**Comment by LipkeGu** [comment]
https://github.com/LipkeGu/TSIniFiles "ts_package.zip" contains also the firestorm Content. :)

**Comment by LipkeGu** [comment]
We should also add an ability to choose what units are droped by DropDods, carryall :(
Vanilla TS has the logic for it (SHPs) :)

afaik my idea is:

- option to allow custom reinforcements (limit to 8 units)
- when requesting the droppod, the player could choose what units are dropped 
(tanks comes by carryall / Inf per Pods)

**Comment by LipkeGu** [comment]
#8161 should be added to ```Installation from CD #3883 and asset download #3888```

**Comment by Phrohdoh** [comment]
#8161 is not asset downloading.

**Comment by LipkeGu** [comment]
[ ] Buildlimit per structure is missing in the list <- required by upgrades (Plugable Upgrades)

**Comment by Unit158** [comment]
That's actually already possible.

**Comment by LipkeGu** [comment]
it isnt... in vanilla it wasnt able to place 2 ION plugs on the same Upgrade centre :( one per centre... afaik i also asked friends and they remember also that it was only possible to build one upgrade per centre

**Comment by penev92** [comment]
This is an issue for tracking what features need to be implemented. The build limit is possible. What you are talking about is simple polish.

**Comment by pchote** [comment]
> it isnt... in vanilla it wasnt able to place 2 ION plugs on the same Upgrade centre

Vanilla TS does allow this - I specifically tested this while building our version of the upgrade plugs.

**Comment by SMIFFGIG** [comment]
LipkeGu you're wrong I'm afraid :-)
You can certainly build two identical plugins for structures (GAPLUG more specifically) in TS and FS.
Not that there is any point.

**Comment by LipkeGu** [comment]
#12088

**Comment by pchote** [comment]
Most of these issues have their own tickets that can be filtered by the `Tiberian Sun` label in the issue list, and the ones that don't should.  Closing this as it is no longer necessary.

**Comment by Mailaender** [comment]
Added some more tickets with references for features listed here.

**Comment by reaperrr** [comment]
For `Weapon spawning from airburst` we should probably try adapting @GraionDilach's [FireShrapnelWarhead](https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/Warheads/FireShrapnelWarhead.cs). FireClusterWarhead is unsuitable, code-wise, though the name might fit better for our presumable main uses (TS Cluster-, Chemical- and Cyborg Reaper missiles).

**Comment by GraionDilach** [comment]
Ungh. I really don't like the implication of name-conflicting there - also note that RA2 had FCW as cluster logic. Although indeed, I was also opting for carrying FSW over back at #11624 when I closed it, because of the impacttypes prerequisite.

**Comment by reaperrr** [comment]
Well, we might as well stick to `FireShrapnelWarhead`, if there are no strong arguments against it. Now that I think about it, your FCW would probably be a better fit for the Chemical Missile, since it spawned gas clouds on 3x3 cells in the original, iirc, so we might need both warhead types (or investigate fusing them).

**Comment by ghost** [comment]
Hello. So, there is closed issue of unofficial Tiberium Sun support? Is it playable?

**Comment by abcdefg30** [comment]
No, it is not yet playable, we have https://github.com/OpenRA/OpenRA/milestone/21 to track this now.
