### ISSUE TITLE
Improve support for external mods

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8993]
- [x] Add engine and required-mod version checks. [#8991]
- [x] Support mods loaded from the support directory. [#8992]
- [ ] Support oramod version checks and upgrades from the mod chooser. [#9028]
- [ ] Support oramod installation via an `openra-mod://` URI. [#9029]
##

**Comment by Phrohdoh** [comment]
Will we update via a direct link to a `.oramod` that is saved and unpacked into the support directory (or possibly kept packed and loaded from zip)?

As an extension idea related to bullet point 3 I'd like to see a place in the UI and in the mod directory for a changelog file that mod authors can include (not necessary!) that players can read and make the decision to upgrade or not based on the information provided.

**Comment by Mailaender** [comment]
The current best practice for vanilla Tiberian Sun mods is to have a spawner which checks for updates and has a button to automatically download and install those. We were asked if such a content delivery feature (like we do for mods) is planned for OpenRA as well. http://www.ppmforums.com/viewtopic.php?p=533798#533798 You might want to take that into consideration.

**Comment by reaperrr** [comment]
#11326 would also improve support for external mods a bit, in my opinion.

**Comment by pchote** [comment]
The remaining issues have been closed, so this is now complete.
