### ISSUE TITLE
Dune 2 mod TODO list

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#9580]
This is a list of all things that will be needed to create a dune2 Mod: (Not complete)
## Adding support for file formats:

required:
- [x] *.PAK (#9580) (Daragon Unpaker is also a good tool to open them)
- [x] D2 SHP Format 2 ( supported by openra) (FINALE.PAK)
- [x] tiles orientation issues implemented (#9723, #9770)
- [x] player palette remap (#9654, #9662)
- [x] *.ICN (in the d2mod)
- [x] *.VOC #10032 (Sounds, music?) (ATRE.PAK, HARK.PAK, HERC.PAK, INTROVOC.PAK, MERC.PAK, Ordos.PAK, VOC.PAK, XTRE.PAK)
- [x] *.WSA #6781 (FINALE_PAK, INTRO.PAK, MENTAT.PAK)
- [x] *.CPS ?? 
- [ ] *.FNT (?maybe some font) #11566
- [ ] *.PAL (BENE.PAL, INTRO.PAL, WESTWOOD.PAL, IBM.PAL)
- [ ] *.INI  (SCENARIO_PAK) (Old Missions)
- [ ] *.EMC
- [ ] *.CPS
- [ ] *.TBL
- [ ] *.MAP (ICON.MAP (textfile))

SOUND.PAK:
- [ ] *.ADL
- [ ] *.ADV
- [ ] *.C55
- [ ] *.DRV (some Drivers)
- [ ] *. PCS
- [ ] *.TAN
- [ ] *.XMI

maybe unnecessary:
- [ ] *.CFG  ( I guess we don't need the confic-files: Dune.CFG, Options.CFG)
- [ ] *.DAT (OneTime.DAT, Waveset.DAT)
- [ ] *.DIP (SETUPENG.DIP)
- [ ] *.ENG (CREDITS.ENG & ENGLISH.PAK ) // Maybe more Localisation files inside the pak's
## Tileset 
- [x] Create the Dune2 Terrain Tileset
- [x] add Crater
- [x] add Spice
- [ ] Add Spicebloom
- [x] Create Test map
## Add Factions
- [x] Adreides
- [x] Ordos
- [x] Harkonnen
- [ ] Imperator
## Add all Buildings:
- [x] Barracks
- [ ] Concrete Slab 
- [x] Construction Yard 
- [x] Heavy Factory
- [x] High Tech Factory
- [x] IX
- [x] Light Factory
- [x] Outpost 
- [x] Palace 
- [x] Repair Facility
- [x] Rocket Turret 
- [x] Spice Refinery 
- [ ] Spice Silos 
- [x] Starport
- [x] Turret 
- [x] Wall
- [x] Wind Trap
- [x] WOR
## add foot Unit
- [x] Heavy Troopers 
- [x] Light Infantry 
- [ ] Fremen
- [ ] Saboteur
- [x] Sardaukar
## add wheeled Units
- [x] MCV 
- [x] Quad
- [x] Trike
- [x] Raider
- [ ] Flaktrike from dune2tgp?
## add chained units
- [x] Combat Tank
- [x] Harvester 
- [x] Missile Tank
- [x] Siege Tank
- [x] Devastator
- [x] Deviator
- [x] Sonic Tank
## add Air Units
- [x] Carryall
- [x] Ornithopter
- [ ] missiles (make units shoot)
## Explosions
- [ ] explosions of units
- [ ] explosions of buildings
## Husks
- [ ] Carryall Husks
- [ ] Ornithopter Husks
## Special stuff
- [x] Deploy support / animation of the MCV 
- [x] Harvester can harvest Spice
- [ ] Harvesters can use a Spice Refinery (pos, orientation)
- [ ] Carryall can lift Harvester
- [ ] Carryall dops harvesters perfect at the Spice Refinery 
- [ ] Repair Facility can Repair units
- [x] add craters on concrete slabs 
- [x] add craters on dunes
- [x] add add footprints for the vehicles (like #5858, #11112)
- [x] fire and smoke animations on damaged vehicles
- [x] fire and smoke animations on damaged buildings
- [x] creation animation for buildings
- [ ] Death Hand
- [x] Sand Worm (Spawn, Attack)
- [x] Function to render pixels randomly (used for worms and sonic-wave missiles)
- [ ] Sand Worm (Look)
- [ ] Sonic-wave animation (Look)
- [ ] Add Fregatte to Starport
- [ ] Add typical Starport ordering #7055
- [x] fog of war
## add Audio
- [ ] add music
- [ ] add sounds of units (Move/Attack-Orders)
- [ ] The vocals are very short and mixed to senctence: maybe we need extra code here 
- [ ] add sounds for messages like (ordos unit destoryed)
## create fitting User Interface (grey #4275, orange #4274)
- [ ] create asstets for menu
- [ ] create HUD for normal gameplay
- [ ] create c&c like sized icons
- [ ] create mouse original courser
## Balancing
- [ ] Add price
- [ ] Add building time
- [ ] Add building range to Conyard
- [ ] Add view range to Buildings
- [ ] Add view range to units
- [ ] Add power consumption
## Techtrees for the Factions
- [ ] Add Techtree for Adreides
- [ ] Add Techtree for Ordos
- [ ] Add Techtree for Harkonnen
- [ ] Add Fremen, Deathhand, Saboteur related to the palace building
- [ ] Add Techtree for Impterator ?
##

**Comment by evgeniysergeev** [comment]
tiles orientation issues implemented in #9723 and #9770

**Comment by evgeniysergeev** [comment]
player palette remap done in #9654

**Comment by evgeniysergeev** [comment]
.ICN file format ready but will be in d2 mod
D2 .SHP file format currently supported by opera

Buldings: wind trap need palette animation
conyard need transformation support

also add craters both on concrete slabs and on dunes
add footprints for the vehicles. 
fire and smoke animations on damaged vehicles and buildings
creation animation for buildings
fog of war

questions: use d2k cursor or original d2 cursor?

**Comment by penev92** [comment]
Original cursors, of course ;)

**Comment by TheRaffy** [comment]
Thanks for the Update! I think the windtraps could use the water animation of the terrain. That could look like what we like to see, but better would be a new palette.Theres already a red done with a palett rotation. Think that was at the ra refinery, but not sure.

**Comment by TheRaffy** [comment]
Are these normal animations of buildings a problem? Like the little flags, or the unitcompleted animations of the Heavy Factory or Light Factory. Not sure about the details, just that they had animations.

**Comment by TheRaffy** [comment]
I Opened the .PAK Fieles with thte Dragon unPacker and updatet a bit.

**Comment by Micr0Bit** [comment]
i assume #11112 is essential for "Special Stuff --> add footprints for the vehicles"

**Comment by TheRaffy** [comment]
updated (footprints reference)

**Comment by Micr0Bit** [comment]
@evgeniysergeev : is there any public way to get in contact with you ? you did send me a gif about dune2 ... but theres actually 4 people sharing lots of love for this game ... @x-a-n-a-x , @SoScared , @TheRaffy and me ... everyone of us would be pleased to see every small progress ... so i will leave this link here for everyone ... 

cause its pretty amazing ... dude

https://streamable.com/hkdj

**Comment by x-a-n-a-x** [comment]
@Micr0Bit : evgeniysergeev was on IRC yesterday and he shared this video on the channel. 
BTW, he also shared another screencast with doublepixel enabled: https://streamable.com/mdy5      

I think he can contact us on IRC (btw we also have IRC logs) and continue sharing his progresses on this github issue: #3274 

evgeniysergeev would like a https://github.com/OpenRA/Dune2 repository to be created.

**Comment by yaaaaa** [comment]
it's very nice gameplay video! great work, great engine =)
when we will can try dev version of this mod?
https://github.com/OpenRA/Dune2 repository is 404 error

**Comment by TheRaffy** [comment]
Wow, stunning. A lot progress has been made. Im rly impressed!

**Comment by SoScared** [comment]
Astounding!

**Comment by evgeniysergeev** [comment]
#11206

**Comment by Micr0Bit** [comment]
@evgeniysergeev : @abcdefg30 gave me the hint that  "QuantizedFacings" https://github.com/OpenRA/OpenRA/wiki/Traits#bodyorientation is there to tune down the movement-directions .... 

cause your vehicles are basicly "sliding" over the battlefield (using the same directions as in dune2000)... although they should only use 8 directions

**Comment by Micr0Bit** [comment]
https://github.com/OpenRA/d2

**Comment by Mailaender** [comment]
Closing here then.
