### ISSUE TITLE
A few ideas for map editor

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#9935]
As discussed in IRC, the following features would be really useful for the map editor:
- [ ] A tile size setting for the item you are placing (useful for ore, could place a 10x10 square for example)
- [ ] A mirror function, so that you can design half of the map and then mirror it (vertically/horizontally/diagonally, this wouldn't have to mirror the sprites, just place them in the relevant places)
- [ ] Range indicators when placing units (idea courtesy of r34ch on IRC)
##

**Comment by pchote** [comment]
That first one could be controlled via the scrollwheel while the resource brush is active.

**Comment by AMHOL** [comment]
That would be a much nicer interface for it :+1:

**Comment by AMHOL** [comment]
Been thinking more about the mirroring function, it would be cool if you could add any number of intersections through the centre of the map, so you could split it up into say, 8 triangles (kind of), then you could concentrate on building the experience for one player, and everything you place would be duplicated in each intersection building a perfectly symmetric map. Would make map creation much easier.

**Comment by Mailaender** [comment]
Like #12522 this is a rather unstructured list containing multiple ideas that should be split into individual tickets to become manageable and easier to search. Closing here and opened #14053 which was requested in both wishlists.
